FROM archlinux-gui:1.2.0

# Update repository and system.
RUN pacman -Syu --noconfirm

# Install web browser Firefox.
RUN pacman -S firefox --noconfirm

# Default command after starting this container.
CMD dbus-run-session firefox
